In [3]:
import pandas as pd
df = pd.read_csv("C:/Users/sidha/Downloads/retail_data/retail_store_sales.csv")

In [14]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [16]:
df.shape

(12575, 11)

In [18]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='str')

In [19]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [4]:
df[df['Price Per Unit'].isnull()][['Quantity', 'Total Spent']].isnull().sum()

Quantity       0
Total Spent    0
dtype: int64

In [5]:
df[df['Quantity'].isnull()][['Total Spent', 'Price Per Unit']].isnull().sum()

Total Spent       604
Price Per Unit      0
dtype: int64

In [6]:
df[df['Quantity'].isnull()]['Price Per Unit'].isnull().sum()

np.int64(0)

In [7]:
(df['Quantity'].isnull() & df['Total Spent'].notnull()).sum()

np.int64(0)

In [8]:
(df['Quantity'].notnull() & df['Total Spent'].isnull()).sum()

np.int64(0)

In [9]:
df[df['Price Per Unit'].isnull()][['Quantity', 'Total Spent']].notnull().sum()

Quantity       609
Total Spent    609
dtype: int64

In [10]:
df['Price Per Unit'].isnull().sum()

np.int64(609)

In [11]:
mask = df['Price Per Unit'].isnull()
df.loc[mask, 'Price Per Unit'] = df.loc[mask, 'Total Spent'] / df.loc[mask, 'Quantity']

In [12]:
df['Price Per Unit'].isnull().sum()

np.int64(0)

In [13]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit         0
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [16]:
df[df['Item'].isnull()]['Category'].isnull().sum()

np.int64(0)

In [17]:
df['Item'] = df['Item'].fillna('Unknown Item')

In [18]:
df['Item'].isnull().sum()

np.int64(0)

In [19]:
df['is_incomplete'] = df['Quantity'].isnull()

In [20]:
df['is_incomplete'].sum()

np.int64(604)

In [21]:
df.head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,is_incomplete
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,False
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,False
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,False
5,TXN_7482416,CUST_09,Patisserie,Unknown Item,20.0,10.0,200.0,Credit Card,Online,2023-11-30,NaN,False
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True,False
7,TXN_1372952,CUST_21,Furniture,Unknown Item,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True,True
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False,False

In [22]:
df['Discount Applied'].unique()

array([True, False, nan], dtype=object)

In [23]:
df['discount_unrecorded'] = df['Discount Applied'].isnull()

In [24]:
df.head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,is_incomplete,discount_unrecorded
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,False,False
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,False,False
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,False,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,False,True
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,False,False
5,TXN_7482416,CUST_09,Patisserie,Unknown Item,20.0,10.0,200.0,Credit Card,Online,2023-11-30,NaN,False,True
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True,False,False
7,TXN_1372952,CUST_21,Furniture,Unknown Item,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True,True,False
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False,False,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False,False,False

In [25]:
df['Discount Applied'] = df['Discount Applied'].fillna(False)

In [26]:
df['Discount Applied'].isnull().sum()

np.int64(0)

In [27]:
df.rename(columns={'is_incomplete': 'missing_quantity_and_total'}, inplace=True)

In [28]:
df.head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,missing_quantity_and_total,discount_unrecorded
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,False,False
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,False,False
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,False,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,False,False,True
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,False,False
5,TXN_7482416,CUST_09,Patisserie,Unknown Item,20.0,10.0,200.0,Credit Card,Online,2023-11-30,False,False,True
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True,False,False
7,TXN_1372952,CUST_21,Furniture,Unknown Item,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True,True,False
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False,False,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False,False,False

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df['Transaction ID'].duplicated().sum()

np.int64(0)

In [31]:
df.dtypes

Transaction ID                    str
Customer ID                       str
Category                          str
Item                              str
Price Per Unit                float64
Quantity                      float64
Total Spent                   float64
Payment Method                    str
Location                          str
Transaction Date                  str
Discount Applied               object
missing_quantity_and_total       bool
discount_unrecorded              bool
dtype: object

In [32]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [33]:
df.dtypes

Transaction ID                           str
Customer ID                              str
Category                                 str
Item                                     str
Price Per Unit                       float64
Quantity                             float64
Total Spent                          float64
Payment Method                           str
Location                                 str
Transaction Date              datetime64[us]
Discount Applied                      object
missing_quantity_and_total              bool
discount_unrecorded                     bool
dtype: object

In [34]:
df.head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,missing_quantity_and_total,discount_unrecorded
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,False,False
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,False,False
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,False,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,False,False,True
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,False,False
5,TXN_7482416,CUST_09,Patisserie,Unknown Item,20.0,10.0,200.0,Credit Card,Online,2023-11-30,False,False,True
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True,False,False
7,TXN_1372952,CUST_21,Furniture,Unknown Item,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True,True,False
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False,False,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False,False,False

In [35]:
df['Discount Applied'] = df['Discount Applied'].astype(bool)

In [36]:
df.dtypes

Transaction ID                           str
Customer ID                              str
Category                                 str
Item                                     str
Price Per Unit                       float64
Quantity                             float64
Total Spent                          float64
Payment Method                           str
Location                                 str
Transaction Date              datetime64[us]
Discount Applied                        bool
missing_quantity_and_total              bool
discount_unrecorded                     bool
dtype: object

In [37]:
mismatch = df[df['missing_quantity_and_total'] == False].copy()
mismatch['calculated_total'] = mismatch['Price Per Unit'] * mismatch['Quantity']
(mismatch['calculated_total'].round(2) != mismatch['Total Spent'].round(2)).sum()

np.int64(0)

In [38]:
df.to_csv('cleaned_sales.csv', index=False)